title: Nate Allen # your name (or website title) here
logo: "/images/UserPicture.png?raw=true" # your photo (or logo) here
description: >
  <br>
  <div>
    <strong>Get in touch:</strong>
    <br>
    <a href="mailto:nallen@patchmaker-collab.com" style="text-decoration: none; color: #0072b1;">
      nallen@patchmaker-collab.com
    </a>
  </div>
  <br>
  <div style="display: flex; align-items: center; gap: 8px;">
    <a href="https://www.linkedin.com/in/nate-allen-234ab099" target="_blank">
      <img src="/assets/icons/linkedin.svg" alt="LinkedIn" style="width:24px; height:auto;">
    </a>
    <a href="https://www.linkedin.com/in/nate-allen-234ab099" target="_blank" style="text-decoration: none; color: inherit;">
      View My LinkedIn Profile
    </a>
  </div>
  <br>
  <div style="display: flex; align-items: center; gap: 8px;">
    <a href="/pdf/Resume.pdf" target="_blank">
      <img src="/assets/icons/resumeicon.svg" alt="Resume" style="width:24px; height:auto;">
    </a>
    <a href="/pdf/Resume.pdf" target="_blank" style="text-decoration: none; color: inherit;">
      View My Resume
    </a>
  </div>
  <br>
  A results-driven Data Analyst with a strong background in leveraging the Microsoft Power Platform to develop data-driven solutions that streamline workflows, enhance decision-making, and drive operational efficiency. With experience in both government and grassroots initiatives, including the Peace Corps, he combines technical expertise with a user-centered, problem-solving approach to create innovative and impactful solutions at all levels.
  <br>
  <div style="display: flex; align-items: center; gap: 8px;">
  <img src="/assets/icons/pl300.png" alt="PL-300 Certificate" style="width:100px; height:auto;">
  <img src="/assets/icons/pl900.png" alt="PL-900 Certificate" style="width:100px; height:auto;">
  </div>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
