title: Nate Allen # your name (or website title) here
logo: "/images/UserPicture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A results-driven Data Analyst with a strong background in leveraging the Microsoft Power Platform to develop data-driven solutions that streamline workflows, enhance decision-making, and drive operational efficiency. With experience in both government and grassroots initiatives, including the Peace Corps, he combines technical expertise with a user-centered, problem-solving approach to create innovative and impactful solutions at all levels.
  <br><br>
  <a href="/pdf/Resume.pdf" target="_blank">Resume</a> 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.linkedin.com/in/example/" target="_blank">
    <img src="/assets/icons/linkedin.svg" alt="Linked-In" style="width:50%;"> 
  </a>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
